[package]
name = "qmassa"
version = "2.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Terminal-based tool for displaying GPUs usage stats on Linux."
keywords = ["gpu", "graphics", "statistics", "usage"]
categories = ["command-line-utilities", "graphics"]
readme = "README.md"

[dependencies]
qmlib = { version = "2.2.2", path = "../qmlib" }
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
crossterm = "0.29.0"
env_logger = "0.11.11"
itertools = "0.14.0"
libc = "0.2.189"
log = "0.4.33"
plotters = { version = "0.3.7", default-features = false, features = ["line_series", "svg_backend"] }
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tui-scrollview = "0.6.7"

[lints]
workspace = true
